name:                diagrams-demo
version:             0.1.0.0
github:              "EugeneN/diagrams-demo"
license:             BSD3
author:              "Eugene Naumenko"
maintainer:          "eugene@traversable.one"
copyright:           "2019 Eugene Naumenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EugeneN/diagrams-demo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  diagrams-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diagrams-demo
    - diagrams
    - diagrams-svg
    - diagrams-lib
    - diagrams-core
    - SVGFonts

tests:
  diagrams-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diagrams-demo
